### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by yielde** [HellOwhatAs/bili_rtmp#1]
大佬牛的，用这个跑了再OBS就可以了。但是推流码跟F12拿到的一模一样，能简要说下是啥原理吗，膜拜~

**Comment by HellOwhatAs** [comment]
不敢当qwq

这个的原理是：用 mitmproxy 做代理，记录下了web端开播和关播请求的全部参数，用 pickle 保存了
然后再用的时候 requests 用同样的请求重新发一遍
没考虑 cookie 过期啥的

我后来不想依赖浏览器，就重新写了下 https://github.com/HellOwhatAs/bili-live 

参考了这里：https://github.com/SocialSisterYi/bilibili-API-collect

**Comment by HellOwhatAs** [comment]
> 但是推流码跟F12拿到的一模一样

在web直播端，网页开播之后也在推流，所以OBS不行

**Comment by yielde** [comment]
受教了，感谢~，我可以这样理解吗：
1. 我之前是F12点击开播拿到推流码，然后点击关闭直播，再去OBS使用推流码这个操作是无效的（点了关闭B站服务器会做下下播的标记把给我生成的推流码清掉了）。
2. web端点击开播包含（请求推流码和开始推流），用脚本直接请求相当于把请求推流码和开始推流解耦，这样我在跑完脚本后，推流码过期时间之前再去用OBS推流就成功了

**Comment by HellOwhatAs** [comment]
对的

**Comment by LiuZHolmes** [comment]
> 不敢当qwq
> 
> 这个的原理是：用 mitmproxy 做代理，记录下了web端开播和关播请求的全部参数，用 pickle 保存了 然后再用的时候 requests 用同样的请求重新发一遍 没考虑 cookie 过期啥的
> 
> 我后来不想依赖浏览器，就重新写了下 https://github.com/HellOwhatAs/bili-live （也还没做 cookie 刷新）
> 
> 参考了这里：https://github.com/SocialSisterYi/bilibili-API-collect

想请问下，没做cookie刷新的意思是拿到的推流码直播久了可能会断掉吗

**Comment by HellOwhatAs** [comment]
@LiuZHolmes cookie 刷新的意思参照[这里](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/login/cookie_refresh.md)

保质期还挺久的  
举例来说我今天登录保存的cookie可能25年2月才会过期（如果按照 `Expires` 字段来看的话）

**Comment by yielde** [comment]
@LiuZHolmes 我也用了至少半个月了，没遇到有cookie的问题，一直可用
